
language: c

compiler: gcc

addons:
  postgresql: "9.3"

env:
  global:
    - secure: cDfB188ECmloGfScZQezqwiFef7l+gXgn2RiTOxINriy9wYS6RmZxuZBHGuR36u7QV3QEJtMdihyQ+XBN2eQPf5jULQXV15t7gArXEVPzzF8i+f8MTgVHugU3TqmPLQkY94wBBbpzvRD9xCAC/uNiQcLLwuD2SjPfTXkqgqqtd0=
    - PGVERSION="9.3"
    - CK_DEFAULT_TIMEOUT=20
    - PLATFORM=ubuntu12
    - ARCH=x86_64
    - RENCI_URL=ftp://ftp.renci.org
    - WTSI_NPG_URL=https://github.com/wtsi-npg/irods
    - PG_PLUGIN_VERSION=1.6
  matrix:
    - IRODS_VERSION=3.3.1
    - IRODS_VERSION=4.1.6

before_install:
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

before_script:
  - source ./scripts/travis_before_script.sh
  - ienv
  - ilsresc -l
  - ils

script:
  - ./scripts/travis_script.sh

after_script:
  - ./scripts/travis_after_script.sh

after_success:
  - make dist
  - export DIST_FILE=$(ls baton-*.tar.gz)
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
